# fly.toml app configuration file generated for server-silent-darkness-2099 on 2026-02-26T14:32:45+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-silent-darkness-2099'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
    method = "get"
    path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
