// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AgentHeartbeatArgs {
    pub agent_id: String,
}

impl From<AgentHeartbeatArgs> for super::Reducer {
    fn from(args: AgentHeartbeatArgs) -> Self {
        Self::AgentHeartbeat {
            agent_id: args.agent_id,
        }
    }
}

impl __sdk::InModule for AgentHeartbeatArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `agent_heartbeat`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait agent_heartbeat {
    /// Request that the remote module invoke the reducer `agent_heartbeat` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`agent_heartbeat:agent_heartbeat_then`] to run a callback after the reducer completes.
    fn agent_heartbeat(&self, agent_id: String) -> __sdk::Result<()> {
        self.agent_heartbeat_then(agent_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `agent_heartbeat` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn agent_heartbeat_then(
        &self,
        agent_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl agent_heartbeat for super::RemoteReducers {
    fn agent_heartbeat_then(
        &self,
        agent_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AgentHeartbeatArgs { agent_id }, callback)
    }
}
