// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AppendMessagePartArgs {
    pub message_id: String,
    pub part_index: u32,
    pub content: String,
}

impl From<AppendMessagePartArgs> for super::Reducer {
    fn from(args: AppendMessagePartArgs) -> Self {
        Self::AppendMessagePart {
            message_id: args.message_id,
            part_index: args.part_index,
            content: args.content,
        }
    }
}

impl __sdk::InModule for AppendMessagePartArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `append_message_part`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait append_message_part {
    /// Request that the remote module invoke the reducer `append_message_part` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`append_message_part:append_message_part_then`] to run a callback after the reducer completes.
    fn append_message_part(
        &self,
        message_id: String,
        part_index: u32,
        content: String,
    ) -> __sdk::Result<()> {
        self.append_message_part_then(message_id, part_index, content, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `append_message_part` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn append_message_part_then(
        &self,
        message_id: String,
        part_index: u32,
        content: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl append_message_part for super::RemoteReducers {
    fn append_message_part_then(
        &self,
        message_id: String,
        part_index: u32,
        content: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AppendMessagePartArgs {
                message_id,
                part_index,
                content,
            },
            callback,
        )
    }
}
