// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ArchiveSessionArgs {
    pub session_id: String,
    pub archived: bool,
}

impl From<ArchiveSessionArgs> for super::Reducer {
    fn from(args: ArchiveSessionArgs) -> Self {
        Self::ArchiveSession {
            session_id: args.session_id,
            archived: args.archived,
        }
    }
}

impl __sdk::InModule for ArchiveSessionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `archive_session`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait archive_session {
    /// Request that the remote module invoke the reducer `archive_session` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`archive_session:archive_session_then`] to run a callback after the reducer completes.
    fn archive_session(&self, session_id: String, archived: bool) -> __sdk::Result<()> {
        self.archive_session_then(session_id, archived, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `archive_session` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn archive_session_then(
        &self,
        session_id: String,
        archived: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl archive_session for super::RemoteReducers {
    fn archive_session_then(
        &self,
        session_id: String,
        archived: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ArchiveSessionArgs {
                session_id,
                archived,
            },
            callback,
        )
    }
}
