// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateToolCommandArgs {
    pub tool_call_id: String,
    pub message_id: String,
    pub session_id: String,
    pub agent_id: String,
    pub tool_name: String,
    pub tool_args: String,
    pub status: String,
}

impl From<CreateToolCommandArgs> for super::Reducer {
    fn from(args: CreateToolCommandArgs) -> Self {
        Self::CreateToolCommand {
            tool_call_id: args.tool_call_id,
            message_id: args.message_id,
            session_id: args.session_id,
            agent_id: args.agent_id,
            tool_name: args.tool_name,
            tool_args: args.tool_args,
            status: args.status,
        }
    }
}

impl __sdk::InModule for CreateToolCommandArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_tool_command`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_tool_command {
    /// Request that the remote module invoke the reducer `create_tool_command` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_tool_command:create_tool_command_then`] to run a callback after the reducer completes.
    fn create_tool_command(
        &self,
        tool_call_id: String,
        message_id: String,
        session_id: String,
        agent_id: String,
        tool_name: String,
        tool_args: String,
        status: String,
    ) -> __sdk::Result<()> {
        self.create_tool_command_then(
            tool_call_id,
            message_id,
            session_id,
            agent_id,
            tool_name,
            tool_args,
            status,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_tool_command` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_tool_command_then(
        &self,
        tool_call_id: String,
        message_id: String,
        session_id: String,
        agent_id: String,
        tool_name: String,
        tool_args: String,
        status: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_tool_command for super::RemoteReducers {
    fn create_tool_command_then(
        &self,
        tool_call_id: String,
        message_id: String,
        session_id: String,
        agent_id: String,
        tool_name: String,
        tool_args: String,
        status: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateToolCommandArgs {
                tool_call_id,
                message_id,
                session_id,
                agent_id,
                tool_name,
                tool_args,
                status,
            },
            callback,
        )
    }
}
