// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Message {
    pub id: String,
    pub session_id: String,
    pub user_id: __sdk::Identity,
    pub role: String,
    pub status: String,
    pub error: Option<String>,
    pub prompt_tokens: Option<u64>,
    pub completion_tokens: Option<u64>,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for Message {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Message`.
///
/// Provides typed access to columns for query building.
pub struct MessageCols {
    pub id: __sdk::__query_builder::Col<Message, String>,
    pub session_id: __sdk::__query_builder::Col<Message, String>,
    pub user_id: __sdk::__query_builder::Col<Message, __sdk::Identity>,
    pub role: __sdk::__query_builder::Col<Message, String>,
    pub status: __sdk::__query_builder::Col<Message, String>,
    pub error: __sdk::__query_builder::Col<Message, Option<String>>,
    pub prompt_tokens: __sdk::__query_builder::Col<Message, Option<u64>>,
    pub completion_tokens: __sdk::__query_builder::Col<Message, Option<u64>>,
    pub created_at: __sdk::__query_builder::Col<Message, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Message {
    type Cols = MessageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MessageCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            role: __sdk::__query_builder::Col::new(table_name, "role"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            error: __sdk::__query_builder::Col::new(table_name, "error"),
            prompt_tokens: __sdk::__query_builder::Col::new(table_name, "prompt_tokens"),
            completion_tokens: __sdk::__query_builder::Col::new(table_name, "completion_tokens"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Message`.
///
/// Provides typed access to indexed columns for query building.
pub struct MessageIxCols {
    pub id: __sdk::__query_builder::IxCol<Message, String>,
    pub session_id: __sdk::__query_builder::IxCol<Message, String>,
}

impl __sdk::__query_builder::HasIxCols for Message {
    type IxCols = MessageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MessageIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            session_id: __sdk::__query_builder::IxCol::new(table_name, "session_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Message {}
