// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MessagePart {
    pub id: u64,
    pub message_id: String,
    pub part_index: u32,
    pub content: String,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for MessagePart {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MessagePart`.
///
/// Provides typed access to columns for query building.
pub struct MessagePartCols {
    pub id: __sdk::__query_builder::Col<MessagePart, u64>,
    pub message_id: __sdk::__query_builder::Col<MessagePart, String>,
    pub part_index: __sdk::__query_builder::Col<MessagePart, u32>,
    pub content: __sdk::__query_builder::Col<MessagePart, String>,
    pub created_at: __sdk::__query_builder::Col<MessagePart, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for MessagePart {
    type Cols = MessagePartCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MessagePartCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            message_id: __sdk::__query_builder::Col::new(table_name, "message_id"),
            part_index: __sdk::__query_builder::Col::new(table_name, "part_index"),
            content: __sdk::__query_builder::Col::new(table_name, "content"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `MessagePart`.
///
/// Provides typed access to indexed columns for query building.
pub struct MessagePartIxCols {
    pub id: __sdk::__query_builder::IxCol<MessagePart, u64>,
}

impl __sdk::__query_builder::HasIxCols for MessagePart {
    type IxCols = MessagePartIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MessagePartIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MessagePart {}
