// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReapStaleAgentsArgs {
    pub max_stale_secs: u32,
}

impl From<ReapStaleAgentsArgs> for super::Reducer {
    fn from(args: ReapStaleAgentsArgs) -> Self {
        Self::ReapStaleAgents {
            max_stale_secs: args.max_stale_secs,
        }
    }
}

impl __sdk::InModule for ReapStaleAgentsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `reap_stale_agents`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait reap_stale_agents {
    /// Request that the remote module invoke the reducer `reap_stale_agents` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`reap_stale_agents:reap_stale_agents_then`] to run a callback after the reducer completes.
    fn reap_stale_agents(&self, max_stale_secs: u32) -> __sdk::Result<()> {
        self.reap_stale_agents_then(max_stale_secs, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `reap_stale_agents` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn reap_stale_agents_then(
        &self,
        max_stale_secs: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl reap_stale_agents for super::RemoteReducers {
    fn reap_stale_agents_then(
        &self,
        max_stale_secs: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ReapStaleAgentsArgs { max_stale_secs }, callback)
    }
}
