// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Session {
    pub id: String,
    pub user_id: __sdk::Identity,
    pub owner_token: String,
    pub title: String,
    pub status: String,
    pub model: Option<String>,
    pub system_prompt: Option<String>,
    pub is_archived: bool,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for Session {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Session`.
///
/// Provides typed access to columns for query building.
pub struct SessionCols {
    pub id: __sdk::__query_builder::Col<Session, String>,
    pub user_id: __sdk::__query_builder::Col<Session, __sdk::Identity>,
    pub owner_token: __sdk::__query_builder::Col<Session, String>,
    pub title: __sdk::__query_builder::Col<Session, String>,
    pub status: __sdk::__query_builder::Col<Session, String>,
    pub model: __sdk::__query_builder::Col<Session, Option<String>>,
    pub system_prompt: __sdk::__query_builder::Col<Session, Option<String>>,
    pub is_archived: __sdk::__query_builder::Col<Session, bool>,
    pub created_at: __sdk::__query_builder::Col<Session, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<Session, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Session {
    type Cols = SessionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SessionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            owner_token: __sdk::__query_builder::Col::new(table_name, "owner_token"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            model: __sdk::__query_builder::Col::new(table_name, "model"),
            system_prompt: __sdk::__query_builder::Col::new(table_name, "system_prompt"),
            is_archived: __sdk::__query_builder::Col::new(table_name, "is_archived"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Session`.
///
/// Provides typed access to indexed columns for query building.
pub struct SessionIxCols {
    pub id: __sdk::__query_builder::IxCol<Session, String>,
}

impl __sdk::__query_builder::HasIxCols for Session {
    type IxCols = SessionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SessionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Session {}
