// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetMessageTokensArgs {
    pub message_id: String,
    pub prompt_tokens: u64,
    pub completion_tokens: u64,
}

impl From<SetMessageTokensArgs> for super::Reducer {
    fn from(args: SetMessageTokensArgs) -> Self {
        Self::SetMessageTokens {
            message_id: args.message_id,
            prompt_tokens: args.prompt_tokens,
            completion_tokens: args.completion_tokens,
        }
    }
}

impl __sdk::InModule for SetMessageTokensArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_message_tokens`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_message_tokens {
    /// Request that the remote module invoke the reducer `set_message_tokens` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_message_tokens:set_message_tokens_then`] to run a callback after the reducer completes.
    fn set_message_tokens(
        &self,
        message_id: String,
        prompt_tokens: u64,
        completion_tokens: u64,
    ) -> __sdk::Result<()> {
        self.set_message_tokens_then(message_id, prompt_tokens, completion_tokens, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_message_tokens` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_message_tokens_then(
        &self,
        message_id: String,
        prompt_tokens: u64,
        completion_tokens: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_message_tokens for super::RemoteReducers {
    fn set_message_tokens_then(
        &self,
        message_id: String,
        prompt_tokens: u64,
        completion_tokens: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetMessageTokensArgs {
                message_id,
                prompt_tokens,
                completion_tokens,
            },
            callback,
        )
    }
}
