// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateToolCommandArgsArgs {
    pub tool_command_id: u64,
    pub tool_args: String,
}

impl From<UpdateToolCommandArgsArgs> for super::Reducer {
    fn from(args: UpdateToolCommandArgsArgs) -> Self {
        Self::UpdateToolCommandArgs {
            tool_command_id: args.tool_command_id,
            tool_args: args.tool_args,
        }
    }
}

impl __sdk::InModule for UpdateToolCommandArgsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_tool_command_args`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_tool_command_args {
    /// Request that the remote module invoke the reducer `update_tool_command_args` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_tool_command_args:update_tool_command_args_then`] to run a callback after the reducer completes.
    fn update_tool_command_args(
        &self,
        tool_command_id: u64,
        tool_args: String,
    ) -> __sdk::Result<()> {
        self.update_tool_command_args_then(tool_command_id, tool_args, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_tool_command_args` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_tool_command_args_then(
        &self,
        tool_command_id: u64,
        tool_args: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_tool_command_args for super::RemoteReducers {
    fn update_tool_command_args_then(
        &self,
        tool_command_id: u64,
        tool_args: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateToolCommandArgsArgs {
                tool_command_id,
                tool_args,
            },
            callback,
        )
    }
}
