// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateSessionModelArgs {
    pub session_id: String,
    pub model: Option<String>,
}

impl From<UpdateSessionModelArgs> for super::Reducer {
    fn from(args: UpdateSessionModelArgs) -> Self {
        Self::UpdateSessionModel {
            session_id: args.session_id,
            model: args.model,
        }
    }
}

impl __sdk::InModule for UpdateSessionModelArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_session_model`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_session_model {
    /// Request that the remote module invoke the reducer `update_session_model` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_session_model:update_session_model_then`] to run a callback after the reducer completes.
    fn update_session_model(&self, session_id: String, model: Option<String>) -> __sdk::Result<()> {
        self.update_session_model_then(session_id, model, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_session_model` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_session_model_then(
        &self,
        session_id: String,
        model: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_session_model for super::RemoteReducers {
    fn update_session_model_then(
        &self,
        session_id: String,
        model: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateSessionModelArgs { session_id, model }, callback)
    }
}
