// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Verification {
    pub id: u64,
    pub session_id: String,
    pub message_id: String,
    pub passed: bool,
    pub reason: Option<String>,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for Verification {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Verification`.
///
/// Provides typed access to columns for query building.
pub struct VerificationCols {
    pub id: __sdk::__query_builder::Col<Verification, u64>,
    pub session_id: __sdk::__query_builder::Col<Verification, String>,
    pub message_id: __sdk::__query_builder::Col<Verification, String>,
    pub passed: __sdk::__query_builder::Col<Verification, bool>,
    pub reason: __sdk::__query_builder::Col<Verification, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<Verification, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Verification {
    type Cols = VerificationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        VerificationCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            message_id: __sdk::__query_builder::Col::new(table_name, "message_id"),
            passed: __sdk::__query_builder::Col::new(table_name, "passed"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Verification`.
///
/// Provides typed access to indexed columns for query building.
pub struct VerificationIxCols {
    pub id: __sdk::__query_builder::IxCol<Verification, u64>,
    pub message_id: __sdk::__query_builder::IxCol<Verification, String>,
    pub session_id: __sdk::__query_builder::IxCol<Verification, String>,
}

impl __sdk::__query_builder::HasIxCols for Verification {
    type IxCols = VerificationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        VerificationIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            message_id: __sdk::__query_builder::IxCol::new(table_name, "message_id"),
            session_id: __sdk::__query_builder::IxCol::new(table_name, "session_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Verification {}
