// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CleanupOldSessionsArgs {
    pub max_age_days: u32,
}

impl From<CleanupOldSessionsArgs> for super::Reducer {
    fn from(args: CleanupOldSessionsArgs) -> Self {
        Self::CleanupOldSessions {
            max_age_days: args.max_age_days,
        }
    }
}

impl __sdk::InModule for CleanupOldSessionsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `cleanup_old_sessions`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait cleanup_old_sessions {
    /// Request that the remote module invoke the reducer `cleanup_old_sessions` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`cleanup_old_sessions:cleanup_old_sessions_then`] to run a callback after the reducer completes.
    fn cleanup_old_sessions(&self, max_age_days: u32) -> __sdk::Result<()> {
        self.cleanup_old_sessions_then(max_age_days, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `cleanup_old_sessions` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn cleanup_old_sessions_then(
        &self,
        max_age_days: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl cleanup_old_sessions for super::RemoteReducers {
    fn cleanup_old_sessions_then(
        &self,
        max_age_days: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CleanupOldSessionsArgs { max_age_days }, callback)
    }
}
