// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateVerificationArgs {
    pub session_id: String,
    pub message_id: String,
    pub passed: bool,
    pub reason: Option<String>,
}

impl From<CreateVerificationArgs> for super::Reducer {
    fn from(args: CreateVerificationArgs) -> Self {
        Self::CreateVerification {
            session_id: args.session_id,
            message_id: args.message_id,
            passed: args.passed,
            reason: args.reason,
        }
    }
}

impl __sdk::InModule for CreateVerificationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_verification`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_verification {
    /// Request that the remote module invoke the reducer `create_verification` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_verification:create_verification_then`] to run a callback after the reducer completes.
    fn create_verification(
        &self,
        session_id: String,
        message_id: String,
        passed: bool,
        reason: Option<String>,
    ) -> __sdk::Result<()> {
        self.create_verification_then(session_id, message_id, passed, reason, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_verification` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_verification_then(
        &self,
        session_id: String,
        message_id: String,
        passed: bool,
        reason: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_verification for super::RemoteReducers {
    fn create_verification_then(
        &self,
        session_id: String,
        message_id: String,
        passed: bool,
        reason: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateVerificationArgs {
                session_id,
                message_id,
                passed,
                reason,
            },
            callback,
        )
    }
}
