// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateSessionArgs {
    pub session_id: String,
}

impl From<CreateSessionArgs> for super::Reducer {
    fn from(args: CreateSessionArgs) -> Self {
        Self::CreateSession {
            session_id: args.session_id,
        }
    }
}

impl __sdk::InModule for CreateSessionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_session`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_session {
    /// Request that the remote module invoke the reducer `create_session` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_session:create_session_then`] to run a callback after the reducer completes.
    fn create_session(&self, session_id: String) -> __sdk::Result<()> {
        self.create_session_then(session_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_session` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_session_then(
        &self,
        session_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_session for super::RemoteReducers {
    fn create_session_then(
        &self,
        session_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CreateSessionArgs { session_id }, callback)
    }
}
