// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct FinalizeToolCommandArgs {
    pub tool_call_id: String,
    pub tool_args: String,
}

impl From<FinalizeToolCommandArgs> for super::Reducer {
    fn from(args: FinalizeToolCommandArgs) -> Self {
        Self::FinalizeToolCommand {
            tool_call_id: args.tool_call_id,
            tool_args: args.tool_args,
        }
    }
}

impl __sdk::InModule for FinalizeToolCommandArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `finalize_tool_command`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait finalize_tool_command {
    /// Request that the remote module invoke the reducer `finalize_tool_command` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`finalize_tool_command:finalize_tool_command_then`] to run a callback after the reducer completes.
    fn finalize_tool_command(&self, tool_call_id: String, tool_args: String) -> __sdk::Result<()> {
        self.finalize_tool_command_then(tool_call_id, tool_args, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `finalize_tool_command` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn finalize_tool_command_then(
        &self,
        tool_call_id: String,
        tool_args: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl finalize_tool_command for super::RemoteReducers {
    fn finalize_tool_command_then(
        &self,
        tool_call_id: String,
        tool_args: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            FinalizeToolCommandArgs {
                tool_call_id,
                tool_args,
            },
            callback,
        )
    }
}
