// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::message_part_type::MessagePart;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `message_part`.
///
/// Obtain a handle from the [`MessagePartTableAccess::message_part`] method on [`super::RemoteTables`],
/// like `ctx.db.message_part()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.message_part().on_insert(...)`.
pub struct MessagePartTableHandle<'ctx> {
    imp: __sdk::TableHandle<MessagePart>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `message_part`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MessagePartTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MessagePartTableHandle`], which mediates access to the table `message_part`.
    fn message_part(&self) -> MessagePartTableHandle<'_>;
}

impl MessagePartTableAccess for super::RemoteTables {
    fn message_part(&self) -> MessagePartTableHandle<'_> {
        MessagePartTableHandle {
            imp: self.imp.get_table::<MessagePart>("message_part"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MessagePartInsertCallbackId(__sdk::CallbackId);
pub struct MessagePartDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MessagePartTableHandle<'ctx> {
    type Row = MessagePart;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MessagePart> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MessagePartInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MessagePartInsertCallbackId {
        MessagePartInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MessagePartInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MessagePartDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MessagePartDeleteCallbackId {
        MessagePartDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MessagePartDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MessagePartUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MessagePartTableHandle<'ctx> {
    type UpdateCallbackId = MessagePartUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MessagePartUpdateCallbackId {
        MessagePartUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MessagePartUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `message_part`,
/// which allows point queries on the field of the same name
/// via the [`MessagePartIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.message_part().id().find(...)`.
pub struct MessagePartIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MessagePart, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MessagePartTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `message_part`.
    pub fn id(&self) -> MessagePartIdUnique<'ctx> {
        MessagePartIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MessagePartIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MessagePart> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MessagePart>("message_part");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MessagePart>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MessagePart>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MessagePart`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait message_partQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MessagePart`.
    fn message_part(&self) -> __sdk::__query_builder::Table<MessagePart>;
}

impl message_partQueryTableAccess for __sdk::QueryTableAccessor {
    fn message_part(&self) -> __sdk::__query_builder::Table<MessagePart> {
        __sdk::__query_builder::Table::new("message_part")
    }
}
