// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod agent_disconnect_reducer;
pub mod agent_heartbeat_reducer;
pub mod agent_table;
pub mod agent_type;
pub mod append_message_part_reducer;
pub mod archive_session_reducer;
pub mod cleanup_old_sessions_reducer;
pub mod complete_message_reducer;
pub mod create_session_reducer;
pub mod create_tool_command_reducer;
pub mod create_tool_result_reducer;
pub mod create_verification_reducer;
pub mod delete_message_reducer;
pub mod delete_session_reducer;
pub mod fail_message_reducer;
pub mod finalize_tool_command_reducer;
pub mod message_part_table;
pub mod message_part_type;
pub mod message_table;
pub mod message_type;
pub mod reap_stale_agents_reducer;
pub mod register_agent_reducer;
pub mod send_message_reducer;
pub mod session_table;
pub mod session_type;
pub mod set_message_tokens_reducer;
pub mod tool_command_table;
pub mod tool_command_type;
pub mod tool_result_table;
pub mod tool_result_type;
pub mod update_message_content_reducer;
pub mod update_session_model_reducer;
pub mod update_session_status_reducer;
pub mod update_session_system_prompt_reducer;
pub mod update_session_title_reducer;
pub mod update_tool_command_status_reducer;
pub mod verification_table;
pub mod verification_type;

pub use agent_disconnect_reducer::agent_disconnect;
pub use agent_heartbeat_reducer::agent_heartbeat;
pub use agent_table::*;
pub use agent_type::Agent;
pub use append_message_part_reducer::append_message_part;
pub use archive_session_reducer::archive_session;
pub use cleanup_old_sessions_reducer::cleanup_old_sessions;
pub use complete_message_reducer::complete_message;
pub use create_session_reducer::create_session;
pub use create_tool_command_reducer::create_tool_command;
pub use create_tool_result_reducer::create_tool_result;
pub use create_verification_reducer::create_verification;
pub use delete_message_reducer::delete_message;
pub use delete_session_reducer::delete_session;
pub use fail_message_reducer::fail_message;
pub use finalize_tool_command_reducer::finalize_tool_command;
pub use message_part_table::*;
pub use message_part_type::MessagePart;
pub use message_table::*;
pub use message_type::Message;
pub use reap_stale_agents_reducer::reap_stale_agents;
pub use register_agent_reducer::register_agent;
pub use send_message_reducer::send_message;
pub use session_table::*;
pub use session_type::Session;
pub use set_message_tokens_reducer::set_message_tokens;
pub use tool_command_table::*;
pub use tool_command_type::ToolCommand;
pub use tool_result_table::*;
pub use tool_result_type::ToolResult;
pub use update_message_content_reducer::update_message_content;
pub use update_session_model_reducer::update_session_model;
pub use update_session_status_reducer::update_session_status;
pub use update_session_system_prompt_reducer::update_session_system_prompt;
pub use update_session_title_reducer::update_session_title;
pub use update_tool_command_status_reducer::update_tool_command_status;
pub use verification_table::*;
pub use verification_type::Verification;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AgentDisconnect {
        agent_id: String,
    },
    AgentHeartbeat {
        agent_id: String,
    },
    AppendMessagePart {
        message_id: String,
        part_index: u32,
        content: String,
    },
    ArchiveSession {
        session_id: String,
        archived: bool,
    },
    CleanupOldSessions {
        max_age_days: u32,
    },
    CompleteMessage {
        message_id: String,
    },
    CreateSession {
        session_id: String,
        owner_token: String,
    },
    CreateToolCommand {
        tool_call_id: String,
        message_id: String,
        session_id: String,
        agent_id: String,
        tool_name: String,
        tool_args: String,
        status: String,
    },
    CreateToolResult {
        tool_command_id: u64,
        success: bool,
        output: String,
        error: Option<String>,
    },
    CreateVerification {
        session_id: String,
        message_id: String,
        passed: bool,
        reason: Option<String>,
    },
    DeleteMessage {
        message_id: String,
    },
    DeleteSession {
        session_id: String,
    },
    FailMessage {
        message_id: String,
        error: String,
    },
    FinalizeToolCommand {
        tool_call_id: String,
        tool_args: String,
    },
    ReapStaleAgents {
        max_stale_secs: u32,
    },
    RegisterAgent {
        agent_id: String,
        name: String,
        owner_token: String,
        workdir: String,
        workspace_tree: String,
    },
    SendMessage {
        message_id: String,
        session_id: String,
        role: String,
        status: String,
    },
    SetMessageTokens {
        message_id: String,
        prompt_tokens: u64,
        completion_tokens: u64,
    },
    UpdateMessageContent {
        message_id: String,
        content: String,
    },
    UpdateSessionModel {
        session_id: String,
        model: Option<String>,
    },
    UpdateSessionStatus {
        session_id: String,
        status: String,
    },
    UpdateSessionSystemPrompt {
        session_id: String,
        system_prompt: Option<String>,
    },
    UpdateSessionTitle {
        session_id: String,
        title: String,
    },
    UpdateToolCommandStatus {
        tool_command_id: u64,
        status: String,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AgentDisconnect { .. } => "agent_disconnect",
            Reducer::AgentHeartbeat { .. } => "agent_heartbeat",
            Reducer::AppendMessagePart { .. } => "append_message_part",
            Reducer::ArchiveSession { .. } => "archive_session",
            Reducer::CleanupOldSessions { .. } => "cleanup_old_sessions",
            Reducer::CompleteMessage { .. } => "complete_message",
            Reducer::CreateSession { .. } => "create_session",
            Reducer::CreateToolCommand { .. } => "create_tool_command",
            Reducer::CreateToolResult { .. } => "create_tool_result",
            Reducer::CreateVerification { .. } => "create_verification",
            Reducer::DeleteMessage { .. } => "delete_message",
            Reducer::DeleteSession { .. } => "delete_session",
            Reducer::FailMessage { .. } => "fail_message",
            Reducer::FinalizeToolCommand { .. } => "finalize_tool_command",
            Reducer::ReapStaleAgents { .. } => "reap_stale_agents",
            Reducer::RegisterAgent { .. } => "register_agent",
            Reducer::SendMessage { .. } => "send_message",
            Reducer::SetMessageTokens { .. } => "set_message_tokens",
            Reducer::UpdateMessageContent { .. } => "update_message_content",
            Reducer::UpdateSessionModel { .. } => "update_session_model",
            Reducer::UpdateSessionStatus { .. } => "update_session_status",
            Reducer::UpdateSessionSystemPrompt { .. } => "update_session_system_prompt",
            Reducer::UpdateSessionTitle { .. } => "update_session_title",
            Reducer::UpdateToolCommandStatus { .. } => "update_tool_command_status",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AgentDisconnect { agent_id } => {
                __sats::bsatn::to_vec(&agent_disconnect_reducer::AgentDisconnectArgs {
                    agent_id: agent_id.clone(),
                })
            }
            Reducer::AgentHeartbeat { agent_id } => {
                __sats::bsatn::to_vec(&agent_heartbeat_reducer::AgentHeartbeatArgs {
                    agent_id: agent_id.clone(),
                })
            }
            Reducer::AppendMessagePart {
                message_id,
                part_index,
                content,
            } => __sats::bsatn::to_vec(&append_message_part_reducer::AppendMessagePartArgs {
                message_id: message_id.clone(),
                part_index: part_index.clone(),
                content: content.clone(),
            }),
            Reducer::ArchiveSession {
                session_id,
                archived,
            } => __sats::bsatn::to_vec(&archive_session_reducer::ArchiveSessionArgs {
                session_id: session_id.clone(),
                archived: archived.clone(),
            }),
            Reducer::CleanupOldSessions { max_age_days } => {
                __sats::bsatn::to_vec(&cleanup_old_sessions_reducer::CleanupOldSessionsArgs {
                    max_age_days: max_age_days.clone(),
                })
            }
            Reducer::CompleteMessage { message_id } => {
                __sats::bsatn::to_vec(&complete_message_reducer::CompleteMessageArgs {
                    message_id: message_id.clone(),
                })
            }
            Reducer::CreateSession {
                session_id,
                owner_token,
            } => __sats::bsatn::to_vec(&create_session_reducer::CreateSessionArgs {
                session_id: session_id.clone(),
                owner_token: owner_token.clone(),
            }),
            Reducer::CreateToolCommand {
                tool_call_id,
                message_id,
                session_id,
                agent_id,
                tool_name,
                tool_args,
                status,
            } => __sats::bsatn::to_vec(&create_tool_command_reducer::CreateToolCommandArgs {
                tool_call_id: tool_call_id.clone(),
                message_id: message_id.clone(),
                session_id: session_id.clone(),
                agent_id: agent_id.clone(),
                tool_name: tool_name.clone(),
                tool_args: tool_args.clone(),
                status: status.clone(),
            }),
            Reducer::CreateToolResult {
                tool_command_id,
                success,
                output,
                error,
            } => __sats::bsatn::to_vec(&create_tool_result_reducer::CreateToolResultArgs {
                tool_command_id: tool_command_id.clone(),
                success: success.clone(),
                output: output.clone(),
                error: error.clone(),
            }),
            Reducer::CreateVerification {
                session_id,
                message_id,
                passed,
                reason,
            } => __sats::bsatn::to_vec(&create_verification_reducer::CreateVerificationArgs {
                session_id: session_id.clone(),
                message_id: message_id.clone(),
                passed: passed.clone(),
                reason: reason.clone(),
            }),
            Reducer::DeleteMessage { message_id } => {
                __sats::bsatn::to_vec(&delete_message_reducer::DeleteMessageArgs {
                    message_id: message_id.clone(),
                })
            }
            Reducer::DeleteSession { session_id } => {
                __sats::bsatn::to_vec(&delete_session_reducer::DeleteSessionArgs {
                    session_id: session_id.clone(),
                })
            }
            Reducer::FailMessage { message_id, error } => {
                __sats::bsatn::to_vec(&fail_message_reducer::FailMessageArgs {
                    message_id: message_id.clone(),
                    error: error.clone(),
                })
            }
            Reducer::FinalizeToolCommand {
                tool_call_id,
                tool_args,
            } => __sats::bsatn::to_vec(&finalize_tool_command_reducer::FinalizeToolCommandArgs {
                tool_call_id: tool_call_id.clone(),
                tool_args: tool_args.clone(),
            }),
            Reducer::ReapStaleAgents { max_stale_secs } => {
                __sats::bsatn::to_vec(&reap_stale_agents_reducer::ReapStaleAgentsArgs {
                    max_stale_secs: max_stale_secs.clone(),
                })
            }
            Reducer::RegisterAgent {
                agent_id,
                name,
                owner_token,
                workdir,
                workspace_tree,
            } => __sats::bsatn::to_vec(&register_agent_reducer::RegisterAgentArgs {
                agent_id: agent_id.clone(),
                name: name.clone(),
                owner_token: owner_token.clone(),
                workdir: workdir.clone(),
                workspace_tree: workspace_tree.clone(),
            }),
            Reducer::SendMessage {
                message_id,
                session_id,
                role,
                status,
            } => __sats::bsatn::to_vec(&send_message_reducer::SendMessageArgs {
                message_id: message_id.clone(),
                session_id: session_id.clone(),
                role: role.clone(),
                status: status.clone(),
            }),
            Reducer::SetMessageTokens {
                message_id,
                prompt_tokens,
                completion_tokens,
            } => __sats::bsatn::to_vec(&set_message_tokens_reducer::SetMessageTokensArgs {
                message_id: message_id.clone(),
                prompt_tokens: prompt_tokens.clone(),
                completion_tokens: completion_tokens.clone(),
            }),
            Reducer::UpdateMessageContent {
                message_id,
                content,
            } => __sats::bsatn::to_vec(&update_message_content_reducer::UpdateMessageContentArgs {
                message_id: message_id.clone(),
                content: content.clone(),
            }),
            Reducer::UpdateSessionModel { session_id, model } => {
                __sats::bsatn::to_vec(&update_session_model_reducer::UpdateSessionModelArgs {
                    session_id: session_id.clone(),
                    model: model.clone(),
                })
            }
            Reducer::UpdateSessionStatus { session_id, status } => {
                __sats::bsatn::to_vec(&update_session_status_reducer::UpdateSessionStatusArgs {
                    session_id: session_id.clone(),
                    status: status.clone(),
                })
            }
            Reducer::UpdateSessionSystemPrompt {
                session_id,
                system_prompt,
            } => __sats::bsatn::to_vec(
                &update_session_system_prompt_reducer::UpdateSessionSystemPromptArgs {
                    session_id: session_id.clone(),
                    system_prompt: system_prompt.clone(),
                },
            ),
            Reducer::UpdateSessionTitle { session_id, title } => {
                __sats::bsatn::to_vec(&update_session_title_reducer::UpdateSessionTitleArgs {
                    session_id: session_id.clone(),
                    title: title.clone(),
                })
            }
            Reducer::UpdateToolCommandStatus {
                tool_command_id,
                status,
            } => __sats::bsatn::to_vec(
                &update_tool_command_status_reducer::UpdateToolCommandStatusArgs {
                    tool_command_id: tool_command_id.clone(),
                    status: status.clone(),
                },
            ),
            _ => unreachable!(),
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    agent: __sdk::TableUpdate<Agent>,
    message: __sdk::TableUpdate<Message>,
    message_part: __sdk::TableUpdate<MessagePart>,
    session: __sdk::TableUpdate<Session>,
    tool_command: __sdk::TableUpdate<ToolCommand>,
    tool_result: __sdk::TableUpdate<ToolResult>,
    verification: __sdk::TableUpdate<Verification>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "agent" => db_update
                    .agent
                    .append(agent_table::parse_table_update(table_update)?),
                "message" => db_update
                    .message
                    .append(message_table::parse_table_update(table_update)?),
                "message_part" => db_update
                    .message_part
                    .append(message_part_table::parse_table_update(table_update)?),
                "session" => db_update
                    .session
                    .append(session_table::parse_table_update(table_update)?),
                "tool_command" => db_update
                    .tool_command
                    .append(tool_command_table::parse_table_update(table_update)?),
                "tool_result" => db_update
                    .tool_result
                    .append(tool_result_table::parse_table_update(table_update)?),
                "verification" => db_update
                    .verification
                    .append(verification_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.agent = cache
            .apply_diff_to_table::<Agent>("agent", &self.agent)
            .with_updates_by_pk(|row| &row.id);
        diff.message = cache
            .apply_diff_to_table::<Message>("message", &self.message)
            .with_updates_by_pk(|row| &row.id);
        diff.message_part = cache
            .apply_diff_to_table::<MessagePart>("message_part", &self.message_part)
            .with_updates_by_pk(|row| &row.id);
        diff.session = cache
            .apply_diff_to_table::<Session>("session", &self.session)
            .with_updates_by_pk(|row| &row.id);
        diff.tool_command = cache
            .apply_diff_to_table::<ToolCommand>("tool_command", &self.tool_command)
            .with_updates_by_pk(|row| &row.id);
        diff.tool_result = cache
            .apply_diff_to_table::<ToolResult>("tool_result", &self.tool_result)
            .with_updates_by_pk(|row| &row.id);
        diff.verification = cache
            .apply_diff_to_table::<Verification>("verification", &self.verification)
            .with_updates_by_pk(|row| &row.id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "agent" => db_update
                    .agent
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "message" => db_update
                    .message
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "message_part" => db_update
                    .message_part
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "session" => db_update
                    .session
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "tool_command" => db_update
                    .tool_command
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "tool_result" => db_update
                    .tool_result
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "verification" => db_update
                    .verification
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "agent" => db_update
                    .agent
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "message" => db_update
                    .message
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "message_part" => db_update
                    .message_part
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "session" => db_update
                    .session
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "tool_command" => db_update
                    .tool_command
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "tool_result" => db_update
                    .tool_result
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "verification" => db_update
                    .verification
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    agent: __sdk::TableAppliedDiff<'r, Agent>,
    message: __sdk::TableAppliedDiff<'r, Message>,
    message_part: __sdk::TableAppliedDiff<'r, MessagePart>,
    session: __sdk::TableAppliedDiff<'r, Session>,
    tool_command: __sdk::TableAppliedDiff<'r, ToolCommand>,
    tool_result: __sdk::TableAppliedDiff<'r, ToolResult>,
    verification: __sdk::TableAppliedDiff<'r, Verification>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Agent>("agent", &self.agent, event);
        callbacks.invoke_table_row_callbacks::<Message>("message", &self.message, event);
        callbacks.invoke_table_row_callbacks::<MessagePart>(
            "message_part",
            &self.message_part,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Session>("session", &self.session, event);
        callbacks.invoke_table_row_callbacks::<ToolCommand>(
            "tool_command",
            &self.tool_command,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ToolResult>("tool_result", &self.tool_result, event);
        callbacks.invoke_table_row_callbacks::<Verification>(
            "verification",
            &self.verification,
            event,
        );
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        agent_table::register_table(client_cache);
        message_table::register_table(client_cache);
        message_part_table::register_table(client_cache);
        session_table::register_table(client_cache);
        tool_command_table::register_table(client_cache);
        tool_result_table::register_table(client_cache);
        verification_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "agent",
        "message",
        "message_part",
        "session",
        "tool_command",
        "tool_result",
        "verification",
    ];
}
