// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tool_command_type::ToolCommand;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `tool_command`.
///
/// Obtain a handle from the [`ToolCommandTableAccess::tool_command`] method on [`super::RemoteTables`],
/// like `ctx.db.tool_command()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tool_command().on_insert(...)`.
pub struct ToolCommandTableHandle<'ctx> {
    imp: __sdk::TableHandle<ToolCommand>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tool_command`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ToolCommandTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ToolCommandTableHandle`], which mediates access to the table `tool_command`.
    fn tool_command(&self) -> ToolCommandTableHandle<'_>;
}

impl ToolCommandTableAccess for super::RemoteTables {
    fn tool_command(&self) -> ToolCommandTableHandle<'_> {
        ToolCommandTableHandle {
            imp: self.imp.get_table::<ToolCommand>("tool_command"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ToolCommandInsertCallbackId(__sdk::CallbackId);
pub struct ToolCommandDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ToolCommandTableHandle<'ctx> {
    type Row = ToolCommand;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ToolCommand> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ToolCommandInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ToolCommandInsertCallbackId {
        ToolCommandInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ToolCommandInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ToolCommandDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ToolCommandDeleteCallbackId {
        ToolCommandDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ToolCommandDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ToolCommandUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ToolCommandTableHandle<'ctx> {
    type UpdateCallbackId = ToolCommandUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ToolCommandUpdateCallbackId {
        ToolCommandUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ToolCommandUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `tool_command`,
/// which allows point queries on the field of the same name
/// via the [`ToolCommandIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tool_command().id().find(...)`.
pub struct ToolCommandIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ToolCommand, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ToolCommandTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `tool_command`.
    pub fn id(&self) -> ToolCommandIdUnique<'ctx> {
        ToolCommandIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ToolCommandIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ToolCommand> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ToolCommand>("tool_command");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ToolCommand>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ToolCommand>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ToolCommand`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait tool_commandQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ToolCommand`.
    fn tool_command(&self) -> __sdk::__query_builder::Table<ToolCommand>;
}

impl tool_commandQueryTableAccess for __sdk::QueryTableAccessor {
    fn tool_command(&self) -> __sdk::__query_builder::Table<ToolCommand> {
        __sdk::__query_builder::Table::new("tool_command")
    }
}
