// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ToolCommand {
    pub id: u64,
    pub message_id: String,
    pub session_id: String,
    pub agent_id: String,
    pub tool_name: String,
    pub tool_args: String,
    pub status: String,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for ToolCommand {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ToolCommand`.
///
/// Provides typed access to columns for query building.
pub struct ToolCommandCols {
    pub id: __sdk::__query_builder::Col<ToolCommand, u64>,
    pub message_id: __sdk::__query_builder::Col<ToolCommand, String>,
    pub session_id: __sdk::__query_builder::Col<ToolCommand, String>,
    pub agent_id: __sdk::__query_builder::Col<ToolCommand, String>,
    pub tool_name: __sdk::__query_builder::Col<ToolCommand, String>,
    pub tool_args: __sdk::__query_builder::Col<ToolCommand, String>,
    pub status: __sdk::__query_builder::Col<ToolCommand, String>,
    pub created_at: __sdk::__query_builder::Col<ToolCommand, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<ToolCommand, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ToolCommand {
    type Cols = ToolCommandCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ToolCommandCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            message_id: __sdk::__query_builder::Col::new(table_name, "message_id"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
            tool_name: __sdk::__query_builder::Col::new(table_name, "tool_name"),
            tool_args: __sdk::__query_builder::Col::new(table_name, "tool_args"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ToolCommand`.
///
/// Provides typed access to indexed columns for query building.
pub struct ToolCommandIxCols {
    pub id: __sdk::__query_builder::IxCol<ToolCommand, u64>,
}

impl __sdk::__query_builder::HasIxCols for ToolCommand {
    type IxCols = ToolCommandIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ToolCommandIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ToolCommand {}
