// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateSessionStatusArgs {
    pub session_id: String,
    pub status: String,
}

impl From<UpdateSessionStatusArgs> for super::Reducer {
    fn from(args: UpdateSessionStatusArgs) -> Self {
        Self::UpdateSessionStatus {
            session_id: args.session_id,
            status: args.status,
        }
    }
}

impl __sdk::InModule for UpdateSessionStatusArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_session_status`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_session_status {
    /// Request that the remote module invoke the reducer `update_session_status` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_session_status:update_session_status_then`] to run a callback after the reducer completes.
    fn update_session_status(&self, session_id: String, status: String) -> __sdk::Result<()> {
        self.update_session_status_then(session_id, status, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_session_status` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_session_status_then(
        &self,
        session_id: String,
        status: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_session_status for super::RemoteReducers {
    fn update_session_status_then(
        &self,
        session_id: String,
        status: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateSessionStatusArgs { session_id, status }, callback)
    }
}
