// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateMessageContentArgs {
    pub message_id: String,
    pub content: String,
}

impl From<UpdateMessageContentArgs> for super::Reducer {
    fn from(args: UpdateMessageContentArgs) -> Self {
        Self::UpdateMessageContent {
            message_id: args.message_id,
            content: args.content,
        }
    }
}

impl __sdk::InModule for UpdateMessageContentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_message_content`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_message_content {
    /// Request that the remote module invoke the reducer `update_message_content` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_message_content:update_message_content_then`] to run a callback after the reducer completes.
    fn update_message_content(&self, message_id: String, content: String) -> __sdk::Result<()> {
        self.update_message_content_then(message_id, content, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_message_content` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_message_content_then(
        &self,
        message_id: String,
        content: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_message_content for super::RemoteReducers {
    fn update_message_content_then(
        &self,
        message_id: String,
        content: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateMessageContentArgs {
                message_id,
                content,
            },
            callback,
        )
    }
}
