// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateSessionSystemPromptArgs {
    pub session_id: String,
    pub system_prompt: Option<String>,
}

impl From<UpdateSessionSystemPromptArgs> for super::Reducer {
    fn from(args: UpdateSessionSystemPromptArgs) -> Self {
        Self::UpdateSessionSystemPrompt {
            session_id: args.session_id,
            system_prompt: args.system_prompt,
        }
    }
}

impl __sdk::InModule for UpdateSessionSystemPromptArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_session_system_prompt`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_session_system_prompt {
    /// Request that the remote module invoke the reducer `update_session_system_prompt` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_session_system_prompt:update_session_system_prompt_then`] to run a callback after the reducer completes.
    fn update_session_system_prompt(
        &self,
        session_id: String,
        system_prompt: Option<String>,
    ) -> __sdk::Result<()> {
        self.update_session_system_prompt_then(session_id, system_prompt, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_session_system_prompt` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_session_system_prompt_then(
        &self,
        session_id: String,
        system_prompt: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_session_system_prompt for super::RemoteReducers {
    fn update_session_system_prompt_then(
        &self,
        session_id: String,
        system_prompt: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateSessionSystemPromptArgs {
                session_id,
                system_prompt,
            },
            callback,
        )
    }
}
