// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  userId: __t.identity().name("user_id"),
  ownerToken: __t.string().name("owner_token"),
  workdir: __t.string(),
  workspaceTree: __t.string().name("workspace_tree"),
  status: __t.string(),
  lastHeartbeat: __t.timestamp().name("last_heartbeat"),
  createdAt: __t.timestamp().name("created_at"),
});
