// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  toolCallId: __t.string(),
  messageId: __t.string(),
  sessionId: __t.string(),
  agentId: __t.string(),
  toolName: __t.string(),
  toolArgs: __t.string(),
  status: __t.string(),
};
