// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

/* eslint-disable */
/* tslint:disable */
import {
  type AlgebraicTypeType as __AlgebraicTypeType,
  DbConnectionBuilder as __DbConnectionBuilder,
  type DbConnectionConfig as __DbConnectionConfig,
  DbConnectionImpl as __DbConnectionImpl,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
} from "spacetimedb";

// Import all reducer arg schemas
import AgentDisconnectReducer from "./agent_disconnect_reducer";
import AgentHeartbeatReducer from "./agent_heartbeat_reducer";
import AppendMessagePartReducer from "./append_message_part_reducer";
import ArchiveSessionReducer from "./archive_session_reducer";
import CleanupOldSessionsReducer from "./cleanup_old_sessions_reducer";
import CompleteMessageReducer from "./complete_message_reducer";
import CreateSessionReducer from "./create_session_reducer";
import CreateToolCommandReducer from "./create_tool_command_reducer";
import CreateToolResultReducer from "./create_tool_result_reducer";
import CreateVerificationReducer from "./create_verification_reducer";
import DeleteMessageReducer from "./delete_message_reducer";
import DeleteSessionReducer from "./delete_session_reducer";
import FailMessageReducer from "./fail_message_reducer";
import FinalizeToolCommandReducer from "./finalize_tool_command_reducer";
import ReapStaleAgentsReducer from "./reap_stale_agents_reducer";
import RegisterAgentReducer from "./register_agent_reducer";
import SendMessageReducer from "./send_message_reducer";
import SetMessageTokensReducer from "./set_message_tokens_reducer";
import UpdateMessageContentReducer from "./update_message_content_reducer";
import UpdateSessionModelReducer from "./update_session_model_reducer";
import UpdateSessionStatusReducer from "./update_session_status_reducer";
import UpdateSessionSystemPromptReducer from "./update_session_system_prompt_reducer";
import UpdateSessionTitleReducer from "./update_session_title_reducer";
import UpdateToolCommandArgsReducer from "./update_tool_command_args_reducer";
import UpdateToolCommandStatusReducer from "./update_tool_command_status_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AgentRow from "./agent_table";
import MessagePartRow from "./message_part_table";
import MessageRow from "./message_table";
import SessionRow from "./session_table";
import ToolCommandRow from "./tool_command_table";
import ToolResultRow from "./tool_result_table";
import VerificationRow from "./verification_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  agent: __table(
    {
      name: "agent",
      indexes: [{ name: "id", algorithm: "btree", columns: ["id"] }],
      constraints: [{ name: "agent_id_key", constraint: "unique", columns: ["id"] }],
    },
    AgentRow
  ),
  message: __table(
    {
      name: "message",
      indexes: [
        { name: "id", algorithm: "btree", columns: ["id"] },
        { name: "session_id", algorithm: "btree", columns: ["sessionId"] },
      ],
      constraints: [{ name: "message_id_key", constraint: "unique", columns: ["id"] }],
    },
    MessageRow
  ),
  message_part: __table(
    {
      name: "message_part",
      indexes: [
        { name: "id", algorithm: "btree", columns: ["id"] },
        { name: "message_id", algorithm: "btree", columns: ["messageId"] },
      ],
      constraints: [{ name: "message_part_id_key", constraint: "unique", columns: ["id"] }],
    },
    MessagePartRow
  ),
  session: __table(
    {
      name: "session",
      indexes: [{ name: "id", algorithm: "btree", columns: ["id"] }],
      constraints: [{ name: "session_id_key", constraint: "unique", columns: ["id"] }],
    },
    SessionRow
  ),
  tool_command: __table(
    {
      name: "tool_command",
      indexes: [
        { name: "agent_id", algorithm: "btree", columns: ["agentId"] },
        { name: "id", algorithm: "btree", columns: ["id"] },
        { name: "message_id", algorithm: "btree", columns: ["messageId"] },
        { name: "session_id", algorithm: "btree", columns: ["sessionId"] },
      ],
      constraints: [{ name: "tool_command_id_key", constraint: "unique", columns: ["id"] }],
    },
    ToolCommandRow
  ),
  tool_result: __table(
    {
      name: "tool_result",
      indexes: [
        { name: "id", algorithm: "btree", columns: ["id"] },
        { name: "tool_command_id", algorithm: "btree", columns: ["toolCommandId"] },
      ],
      constraints: [{ name: "tool_result_id_key", constraint: "unique", columns: ["id"] }],
    },
    ToolResultRow
  ),
  verification: __table(
    {
      name: "verification",
      indexes: [
        { name: "id", algorithm: "btree", columns: ["id"] },
        { name: "message_id", algorithm: "btree", columns: ["messageId"] },
        { name: "session_id", algorithm: "btree", columns: ["sessionId"] },
      ],
      constraints: [{ name: "verification_id_key", constraint: "unique", columns: ["id"] }],
    },
    VerificationRow
  ),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("agent_disconnect", AgentDisconnectReducer),
  __reducerSchema("agent_heartbeat", AgentHeartbeatReducer),
  __reducerSchema("append_message_part", AppendMessagePartReducer),
  __reducerSchema("archive_session", ArchiveSessionReducer),
  __reducerSchema("cleanup_old_sessions", CleanupOldSessionsReducer),
  __reducerSchema("complete_message", CompleteMessageReducer),
  __reducerSchema("create_session", CreateSessionReducer),
  __reducerSchema("create_tool_command", CreateToolCommandReducer),
  __reducerSchema("create_tool_result", CreateToolResultReducer),
  __reducerSchema("create_verification", CreateVerificationReducer),
  __reducerSchema("delete_message", DeleteMessageReducer),
  __reducerSchema("delete_session", DeleteSessionReducer),
  __reducerSchema("fail_message", FailMessageReducer),
  __reducerSchema("finalize_tool_command", FinalizeToolCommandReducer),
  __reducerSchema("reap_stale_agents", ReapStaleAgentsReducer),
  __reducerSchema("register_agent", RegisterAgentReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("set_message_tokens", SetMessageTokensReducer),
  __reducerSchema("update_message_content", UpdateMessageContentReducer),
  __reducerSchema("update_session_model", UpdateSessionModelReducer),
  __reducerSchema("update_session_status", UpdateSessionStatusReducer),
  __reducerSchema("update_session_system_prompt", UpdateSessionSystemPromptReducer),
  __reducerSchema("update_session_title", UpdateSessionTitleReducer),
  __reducerSchema("update_tool_command_args", UpdateToolCommandArgsReducer),
  __reducerSchema("update_tool_command_status", UpdateToolCommandStatusReducer)
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures();

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(
  tablesSchema.schemaType
);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(
      REMOTE_MODULE,
      (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config)
    );
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}
