// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  sessionId: __t.string().name("session_id"),
  userId: __t.identity().name("user_id"),
  role: __t.string(),
  status: __t.string(),
  error: __t.option(__t.string()),
  promptTokens: __t.option(__t.u64()).name("prompt_tokens"),
  completionTokens: __t.option(__t.u64()).name("completion_tokens"),
  createdAt: __t.timestamp().name("created_at"),
});
