// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Agent = __t.object("Agent", {
  id: __t.string(),
  name: __t.string(),
  userId: __t.identity(),
  status: __t.string(),
  lastHeartbeat: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type Agent = __Infer<typeof Agent>;

export const Message = __t.object("Message", {
  id: __t.string(),
  sessionId: __t.string(),
  userId: __t.identity(),
  role: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

export const MessagePart = __t.object("MessagePart", {
  id: __t.u64(),
  messageId: __t.string(),
  partIndex: __t.u32(),
  content: __t.string(),
  createdAt: __t.timestamp(),
});
export type MessagePart = __Infer<typeof MessagePart>;

export const Session = __t.object("Session", {
  id: __t.string(),
  userId: __t.identity(),
  title: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Session = __Infer<typeof Session>;

export const ToolCommand = __t.object("ToolCommand", {
  id: __t.u64(),
  messageId: __t.string(),
  sessionId: __t.string(),
  agentId: __t.string(),
  toolName: __t.string(),
  toolArgs: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ToolCommand = __Infer<typeof ToolCommand>;

export const ToolResult = __t.object("ToolResult", {
  id: __t.u64(),
  toolCommandId: __t.u64(),
  success: __t.bool(),
  output: __t.string(),
  error: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type ToolResult = __Infer<typeof ToolResult>;

