// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AgentDisconnectReducer from "../agent_disconnect_reducer";
import AgentHeartbeatReducer from "../agent_heartbeat_reducer";
import AppendMessagePartReducer from "../append_message_part_reducer";
import ArchiveSessionReducer from "../archive_session_reducer";
import CleanupOldSessionsReducer from "../cleanup_old_sessions_reducer";
import CompleteMessageReducer from "../complete_message_reducer";
import CreateSessionReducer from "../create_session_reducer";
import CreateToolCommandReducer from "../create_tool_command_reducer";
import CreateToolResultReducer from "../create_tool_result_reducer";
import CreateVerificationReducer from "../create_verification_reducer";
import DeleteMessageReducer from "../delete_message_reducer";
import DeleteSessionReducer from "../delete_session_reducer";
import FailMessageReducer from "../fail_message_reducer";
import FinalizeToolCommandReducer from "../finalize_tool_command_reducer";
import ReapStaleAgentsReducer from "../reap_stale_agents_reducer";
import RegisterAgentReducer from "../register_agent_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetMessageTokensReducer from "../set_message_tokens_reducer";
import UpdateMessageContentReducer from "../update_message_content_reducer";
import UpdateSessionModelReducer from "../update_session_model_reducer";
import UpdateSessionStatusReducer from "../update_session_status_reducer";
import UpdateSessionSystemPromptReducer from "../update_session_system_prompt_reducer";
import UpdateSessionTitleReducer from "../update_session_title_reducer";
import UpdateToolCommandArgsReducer from "../update_tool_command_args_reducer";
import UpdateToolCommandStatusReducer from "../update_tool_command_status_reducer";

export type AgentDisconnectParams = __Infer<typeof AgentDisconnectReducer>;
export type AgentHeartbeatParams = __Infer<typeof AgentHeartbeatReducer>;
export type AppendMessagePartParams = __Infer<typeof AppendMessagePartReducer>;
export type ArchiveSessionParams = __Infer<typeof ArchiveSessionReducer>;
export type CleanupOldSessionsParams = __Infer<typeof CleanupOldSessionsReducer>;
export type CompleteMessageParams = __Infer<typeof CompleteMessageReducer>;
export type CreateSessionParams = __Infer<typeof CreateSessionReducer>;
export type CreateToolCommandParams = __Infer<typeof CreateToolCommandReducer>;
export type CreateToolResultParams = __Infer<typeof CreateToolResultReducer>;
export type CreateVerificationParams = __Infer<typeof CreateVerificationReducer>;
export type DeleteMessageParams = __Infer<typeof DeleteMessageReducer>;
export type DeleteSessionParams = __Infer<typeof DeleteSessionReducer>;
export type FailMessageParams = __Infer<typeof FailMessageReducer>;
export type FinalizeToolCommandParams = __Infer<typeof FinalizeToolCommandReducer>;
export type ReapStaleAgentsParams = __Infer<typeof ReapStaleAgentsReducer>;
export type RegisterAgentParams = __Infer<typeof RegisterAgentReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetMessageTokensParams = __Infer<typeof SetMessageTokensReducer>;
export type UpdateMessageContentParams = __Infer<typeof UpdateMessageContentReducer>;
export type UpdateSessionModelParams = __Infer<typeof UpdateSessionModelReducer>;
export type UpdateSessionStatusParams = __Infer<typeof UpdateSessionStatusReducer>;
export type UpdateSessionSystemPromptParams = __Infer<typeof UpdateSessionSystemPromptReducer>;
export type UpdateSessionTitleParams = __Infer<typeof UpdateSessionTitleReducer>;
export type UpdateToolCommandArgsParams = __Infer<typeof UpdateToolCommandArgsReducer>;
export type UpdateToolCommandStatusParams = __Infer<typeof UpdateToolCommandStatusReducer>;

