// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import type { Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import type AgentDisconnectReducer from "../agent_disconnect_reducer";
import type AgentHeartbeatReducer from "../agent_heartbeat_reducer";
import type AppendMessagePartReducer from "../append_message_part_reducer";
import type ArchiveSessionReducer from "../archive_session_reducer";
import type CleanupOldSessionsReducer from "../cleanup_old_sessions_reducer";
import type CompleteMessageReducer from "../complete_message_reducer";
import type CreateSessionReducer from "../create_session_reducer";
import type CreateToolCommandReducer from "../create_tool_command_reducer";
import type CreateToolResultReducer from "../create_tool_result_reducer";
import type CreateVerificationReducer from "../create_verification_reducer";
import type DeleteMessageReducer from "../delete_message_reducer";
import type DeleteSessionReducer from "../delete_session_reducer";
import type FailMessageReducer from "../fail_message_reducer";
import type FinalizeToolCommandReducer from "../finalize_tool_command_reducer";
import type ReapStaleAgentsReducer from "../reap_stale_agents_reducer";
import type RegisterAgentReducer from "../register_agent_reducer";
import type SendMessageReducer from "../send_message_reducer";
import type SetMessageTokensReducer from "../set_message_tokens_reducer";
import type UpdateMessageContentReducer from "../update_message_content_reducer";
import type UpdateSessionModelReducer from "../update_session_model_reducer";
import type UpdateSessionStatusReducer from "../update_session_status_reducer";
import type UpdateSessionSystemPromptReducer from "../update_session_system_prompt_reducer";
import type UpdateSessionTitleReducer from "../update_session_title_reducer";
import type UpdateToolCommandArgsReducer from "../update_tool_command_args_reducer";
import type UpdateToolCommandStatusReducer from "../update_tool_command_status_reducer";

export type AgentDisconnectParams = __Infer<typeof AgentDisconnectReducer>;
export type AgentHeartbeatParams = __Infer<typeof AgentHeartbeatReducer>;
export type AppendMessagePartParams = __Infer<typeof AppendMessagePartReducer>;
export type ArchiveSessionParams = __Infer<typeof ArchiveSessionReducer>;
export type CleanupOldSessionsParams = __Infer<typeof CleanupOldSessionsReducer>;
export type CompleteMessageParams = __Infer<typeof CompleteMessageReducer>;
export type CreateSessionParams = __Infer<typeof CreateSessionReducer>;
export type CreateToolCommandParams = __Infer<typeof CreateToolCommandReducer>;
export type CreateToolResultParams = __Infer<typeof CreateToolResultReducer>;
export type CreateVerificationParams = __Infer<typeof CreateVerificationReducer>;
export type DeleteMessageParams = __Infer<typeof DeleteMessageReducer>;
export type DeleteSessionParams = __Infer<typeof DeleteSessionReducer>;
export type FailMessageParams = __Infer<typeof FailMessageReducer>;
export type FinalizeToolCommandParams = __Infer<typeof FinalizeToolCommandReducer>;
export type ReapStaleAgentsParams = __Infer<typeof ReapStaleAgentsReducer>;
export type RegisterAgentParams = __Infer<typeof RegisterAgentReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetMessageTokensParams = __Infer<typeof SetMessageTokensReducer>;
export type UpdateMessageContentParams = __Infer<typeof UpdateMessageContentReducer>;
export type UpdateSessionModelParams = __Infer<typeof UpdateSessionModelReducer>;
export type UpdateSessionStatusParams = __Infer<typeof UpdateSessionStatusReducer>;
export type UpdateSessionSystemPromptParams = __Infer<typeof UpdateSessionSystemPromptReducer>;
export type UpdateSessionTitleParams = __Infer<typeof UpdateSessionTitleReducer>;
export type UpdateToolCommandArgsParams = __Infer<typeof UpdateToolCommandArgsReducer>;
export type UpdateToolCommandStatusParams = __Infer<typeof UpdateToolCommandStatusReducer>;
