// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AgentDisconnectReducer from "../agent_disconnect_reducer";
import AgentHeartbeatReducer from "../agent_heartbeat_reducer";
import AppendMessagePartReducer from "../append_message_part_reducer";
import CompleteMessageReducer from "../complete_message_reducer";
import CreateSessionReducer from "../create_session_reducer";
import CreateToolCommandReducer from "../create_tool_command_reducer";
import CreateToolResultReducer from "../create_tool_result_reducer";
import FailMessageReducer from "../fail_message_reducer";
import RegisterAgentReducer from "../register_agent_reducer";
import SendMessageReducer from "../send_message_reducer";
import UpdateSessionStatusReducer from "../update_session_status_reducer";
import UpdateSessionTitleReducer from "../update_session_title_reducer";
import UpdateToolCommandStatusReducer from "../update_tool_command_status_reducer";

export type AgentDisconnectParams = __Infer<typeof AgentDisconnectReducer>;
export type AgentHeartbeatParams = __Infer<typeof AgentHeartbeatReducer>;
export type AppendMessagePartParams = __Infer<typeof AppendMessagePartReducer>;
export type CompleteMessageParams = __Infer<typeof CompleteMessageReducer>;
export type CreateSessionParams = __Infer<typeof CreateSessionReducer>;
export type CreateToolCommandParams = __Infer<typeof CreateToolCommandReducer>;
export type CreateToolResultParams = __Infer<typeof CreateToolResultReducer>;
export type FailMessageParams = __Infer<typeof FailMessageReducer>;
export type RegisterAgentParams = __Infer<typeof RegisterAgentReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type UpdateSessionStatusParams = __Infer<typeof UpdateSessionStatusReducer>;
export type UpdateSessionTitleParams = __Infer<typeof UpdateSessionTitleReducer>;
export type UpdateToolCommandStatusParams = __Infer<typeof UpdateToolCommandStatusReducer>;

